### ISSUE TITLE
Error initializing `Adafruit_STMPE610_SPI`

### ISSUE THREAD

**Issue by alex-terry** [adafruit/Adafruit_CircuitPython_STMPE610#17]
**Hardware:**
* [Raspberry Pi 4](https://www.amazon.com/CanaKit-Raspberry-Basic-Kit-2GB/dp/B07TYK4RL8/ref=sr_1_4?dchild=1&keywords=raspberry+pi+4+2gb+kit&qid=1612558278&sr=8-4)
* [STMPE610 Touch Controller](https://www.amazon.com/Sensor-Development-Resistive-Screen-Controller/dp/B00QSJ1TIO/ref=sr_1_1?dchild=1&keywords=Resistive+Touch+Screen+Controller+-+STMPE610&qid=1612558921&sr=8-1)
* [7” touch overlay](https://www.adafruit.com/product/1676)

We are getting this error when we try to run the “simple test” code:

```
Traceback (most recent call last):
  File "../Adafruit_CircuitPython_STMPE610/examples/stmpe610_simpletest.py", line 12, in <module>
    st = Adafruit_STMPE610_SPI(spi, cs)
  File "/home/alex/mtm-chess/env/lib/python3.8/site-packages/adafruit_stmpe610.py", line 278, in __init__
    version = self.get_version
  File "/home/alex/mtm-chess/env/lib/python3.8/site-packages/adafruit_stmpe610.py", line 193, in get_version
    v_1 = self._read_byte(0)
  File "/home/alex/mtm-chess/env/lib/python3.8/site-packages/adafruit_stmpe610.py", line 164, in _read_byte
    return self._read_register(register, 1)[0]
  File "/home/alex/mtm-chess/env/lib/python3.8/site-packages/adafruit_stmpe610.py", line 291, in _read_register
    spi.write(bytearray([register]))
  File "/home/alex/mtm-chess/env/lib/python3.8/site-packages/busio.py", line 317, in write
    return self._spi.write(buf, start, end)
  File "/home/alex/mtm-chess/env/lib/python3.8/site-packages/adafruit_blinka/microcontroller/generic_linux/spi.py", line 81, in write
    self._spi.mode = self.mode
  File "/home/alex/mtm-chess/env/lib/python3.8/site-packages/Adafruit_PureIO/spi.py", line 355, in mode
    self._ioctl(SPI._IOC_WR_MODE, mode)
  File "/home/alex/mtm-chess/env/lib/python3.8/site-packages/Adafruit_PureIO/spi.py", line 224, in _ioctl
    ioctl(self.handle, ioctl_bytes, arg)
OSError: [Errno 22] Invalid argument
```

**We tried:**
- Replacing GPIO wires
- Using a new touch controller
- Using a new touch overlay
- Flipping connection to touch controller

Can you please help? :)

**Comment by ladyada** [comment]
are you running as sudo? are you running the latest version of raspbian OS? did you update *all* pip packages?

**Comment by jerryneedell** [comment]
FYI - I just tried the stmpe610_simpletest on an RPI 400 with CS on D21 and it worked as expected.
I was using an STMPE610 breakout board with an attached touch screen.

I did not have to use sudo...

**Comment by alex-terry** [comment]
Thanks for the quick response!! 

I am running sudo, I am running on Manjaro ARM release 21.01. All pip packages were freshly installed.

**Pip packages:** 
Adafruit-Blinka==6.4.2
adafruit-circuitpython-busdevice==5.0.6
adafruit-circuitpython-stmpe610==1.2.5
Adafruit-PlatformDetect==3.5.0
Adafruit-PureIO==1.1.8
pyftdi==0.52.9
pyserial==3.5
pyusb==1.1.1
rpi-ws281x==4.2.6
RPi.GPIO==0.7.0
sysv-ipc==1.1.0

**Comment by ladyada** [comment]
manjaro isnt supporte, please use raspbian!
